#!/bin/bash

WD=$(dirname $0)
SSL="$WD/ssl"


if [ "$#" -lt 2 ]; then
  echo "Usage: $0 some.domain.name [other.doman.name] [another.domain.name] .."
  exit 1
fi

if [ ! -f "$SSL/ca.key" -o ! -f "$SSL/ca.crt" ]; then
  echo "Error: no $SSL/ca key pair!" >&2
  exit 1
fi

if test -f "$SSL/$1.key" -o -f "$SSL/$1.csr" -o -f "$SSL/$1.crt"; then
  read -p "File $SSL/$1 key/csr/crt exist, continue [y/*]? " -n1 yn
  echo
  test "$yn" = 'y' || exit
fi

SAN=''
for d in "${@:2}"
do
  SAN="$SAN,DNS:$d"
done
SAN=${SAN:1}

echo
echo "Cert (&CN) : $1"
echo "SAN        : $SAN"
read -p "Continue [y/*]? " -n1 yn
echo
test "$yn" = 'y' || exit
echo

openssl req -new -nodes -newkey rsa:2048 -keyout "$SSL/$1.key" -out "$SSL/$1.csr" -subj "/O=$1/CN=$1/" 2> /dev/null \
 && openssl x509 -req -in "$SSL/$1.csr" -CA "$SSL/ca.crt" -CAkey "$SSL/ca.key" -CAcreateserial -CAserial "$SSL/ca.srl" -days 3650 -sha256 -out "$SSL/$1.crt" -extfile <(printf "basicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\nsubjectAltName=$SAN\n") 2>&1 \
 && openssl x509 -noout -text -in "$SSL/$1.crt" \
 || echo 'FAIL!'

chmod 600 "$SSL"/*
