#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 file-to-view"
  exit 1
fi
if [ ! -f "$1" ]; then
  echo "File '$1' doesn't exist!"
  exit 1
fi

case ${1##*.} in
  key) openssl rsa -noout -text -in $1 ;;
  crt) openssl x509 -noout -text -in $1 ;;
  csr) openssl req -noout -text -in $1 ;;
  *)
      echo 'Unknown file format' >&2
      exit 1
esac
